Just Rails 5.0.6 things...
On that particular version, calling isolate_namespace after requiring
browser/engine.rb would result in:

   /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.0.6/lib/action_dispatch/routing.rb:262:in `<module:Routing>': undefined method `squish' for #<String:0x00007f99223d3610> (NoMethodError)
       from /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.0.6/lib/action_dispatch/routing.rb:244:in `<module:ActionDispatch>'
       from /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.0.6/lib/action_dispatch/routing.rb:1:in `<top (required)>'
       from /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:533:in `require'
       from /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:533:in `routes'
       from /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `public_send'
       from /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `method_missing'
       from /Users/pawelpacana/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:383:in `isolate_namespace'
       from /Users/pawelpacana/Code/rails_event_store/rails_event_store-browser/lib/rails_event_store/browser/engine.rb:6:in `<class:Engine>'
       from /Users/pawelpacana/Code/rails_event_store/rails_event_store-browser/lib/rails_event_store/browser/engine.rb:5:in `<module:Browser>'
       from /Users/pawelpacana/Code/rails_event_store/rails_event_store-browser/lib/rails_event_store/browser/engine.rb:4:in `<module:RailsEventStore>'
       from /Users/pawelpacana/Code/rails_event_store/rails_event_store-browser/lib/rails_event_store/browser/engine.rb:3:in `<top (required)>'
       from lib/rails_event_store/browser.rb:6:in `require'
       from lib/rails_event_store/browser.rb:6:in `<main>'

It looks like there's an expectation that String#squish is present and
has already been patched by Rails. After satisfying this requirement,
the output is gone.

Not sure what to do more about it.