Revert lazy-loaded AR, turns out to be more complex
Needs another take, this one was too simplistic.

      NameError: uninitialized constant RubyEventStore::ActiveRecord::WithDefaultModels::EventInStream (NameError)

            [Event, EventInStream]
                    ^^^^^^^^^^^^^

Related:
https://github.com/RailsEventStore/rails_event_store/pull/1906