Time#parse comes from time library.
Explicit require to fix local test runs.

  Failures:

    1) RubyEventStore::Client timestamp is utc time
       Failure/Error: now = Time.parse('2015-05-04 15:17:11 +0200')

       NoMethodError:
         undefined method `parse' for Time:Class
       # ./spec/client_spec.rb:149:in `block (2 levels) in <module:RubyEventStore>'

So far this passed on CI. Assumption - time was somehow required there.
Not worth digging further.