Improve matcher installation docs
TL;DR avoid:
```
LoadError: cannot load such file -- ruby_event_store-rspec
/Users/you/your-pet-project/config/application.rb:7:in `<main>'
/Users/you/your-pet-project/Rakefile:4:in `<main>'
/Users/you/your-pet-project/bin/rails:9:in `<top (required)>'
/Users/you/your-pet-project/bin/spring:15:in `require'
/Users/you/your-pet-project/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
```